In [1]:
import pandas as pd
import numpy as np

## Umgang mit fehlenden Werten 
### Fehlende Werte filtern
NaN - not a number

NA - not available

Null - Wert nicht vorhanden

In [2]:
# Fehlende Werte filtern

data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
print('\n')

print('Boolsches Array mit True falls der Wert fehlt:')
print(data.isna())
print('\n')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


Boolsches Array mit True falls der Wert fehlt:
       0      1      2
0  False  False  False
1  False   True   True
2   True   True   True
3   True  False  False

In [3]:
print('Zeilen mit fehlenden Werte werden gelöscht:')
print(data.dropna())
print('\n')

Zeilen mit fehlenden Werte werden gelöscht:
     0    1    2
0  1.0  6.5  3.0

In [4]:
print('Es werden nur Zeilen gelöscht, wenn alle Werte fehlen:')
print(data.dropna(how="all"))

Es werden nur Zeilen gelöscht, wenn alle Werte fehlen:
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      float64
 1   1       2 non-null      float64
 2   2       2 non-null      float64
dtypes: float64(3)
memory usage: 228.0 bytes

In [6]:
# Daten generieren
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
print(df)

          0         1         2
0 -0.425843       NaN       NaN
1  0.412213       NaN       NaN
2 -1.045613       NaN -0.329342
3  2.574150       NaN -0.860430
4  0.356241 -1.068949 -0.127633
5 -0.890283  0.956249  0.799955
6 -1.029781 -1.649372  0.968829

In [7]:
# Zeilen mit fehlenden Werten löschen
print('\n Zeilen mit fehlenden Werten löschen')
print(df.dropna())

 Zeilen mit fehlenden Werten löschen
          0         1         2
4  0.356241 -1.068949 -0.127633
5 -0.890283  0.956249  0.799955
6 -1.029781 -1.649372  0.968829

In [8]:
# Zeilen mit mindestens 2 fehlenden Werten löschen
print('\n Zeilen mit mindestens 2 fehlenden Werten löschen')
print(df.dropna(thresh=2))

 Zeilen mit mindestens 2 fehlenden Werten löschen
          0         1         2
2 -1.045613       NaN -0.329342
3  2.574150       NaN -0.860430
4  0.356241 -1.068949 -0.127633
5 -0.890283  0.956249  0.799955
6 -1.029781 -1.649372  0.968829

In [9]:
# Spalten mit fehlenden Werten löschen
data[4] = np.nan
print(data)

data.dropna(axis="columns", how="all")

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

### Fehlende Werte ersetzen

In [10]:
# Fehlende Werte mit 0 füllen
print('\n Fehlende Werte mit 0 füllen')
print(df.fillna(0))

 Fehlende Werte mit 0 füllen
          0         1         2
0 -0.425843  0.000000  0.000000
1  0.412213  0.000000  0.000000
2 -1.045613  0.000000 -0.329342
3  2.574150  0.000000 -0.860430
4  0.356241 -1.068949 -0.127633
5 -0.890283  0.956249  0.799955
6 -1.029781 -1.649372  0.968829

In [11]:
# Fehlende Werte in Spalte 1 mit 0.5 ersetzen und in Spalte 2 mit 0, {}: Dictionary
print(df.fillna({1: 0.5, 2: 0}))

          0         1         2
0 -0.425843  0.500000  0.000000
1  0.412213  0.500000  0.000000
2 -1.045613  0.500000 -0.329342
3  2.574150  0.500000 -0.860430
4  0.356241 -1.068949 -0.127633
5 -0.890283  0.956249  0.799955
6 -1.029781 -1.649372  0.968829

In [23]:
# Datensatz erstellen
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan # ab Zeile 2 und Spalte 1 mit NaN füllen
df.iloc[4:, 2] = np.nan # ab Zeile 4 und Spalte 2 mit NaN füllen
df

          0         1         2
0 -0.118880  0.124288 -2.277158
1  0.315536 -0.034330  0.910848
2 -1.759484       NaN  0.073009
3 -0.859975       NaN  0.930137
4  1.334085       NaN       NaN
5 -1.833752       NaN       NaN

In [24]:
# NaN auffüllen mit dem letzten nicht-fehlenden Wert
df_filled = df.ffill()
df_filled.head()

          0         1         2
0 -0.118880  0.124288 -2.277158
1  0.315536 -0.034330  0.910848
2 -1.759484 -0.034330  0.073009
3 -0.859975 -0.034330  0.930137
4  1.334085 -0.034330  0.930137

In [25]:
# forward fill maximal 2 Werte nach dem letzten nicht-fehlenden
print(df.ffill(limit=2))

          0         1         2
0 -0.118880  0.124288 -2.277158
1  0.315536 -0.034330  0.910848
2 -1.759484 -0.034330  0.073009
3 -0.859975 -0.034330  0.930137
4  1.334085       NaN  0.930137
5 -1.833752       NaN  0.930137

In [26]:
# NaN auffüllen mit dem letzten nicht-fehlenden Wert
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
print(data)
data.fillna(data.mean())

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [27]:
# Datensatz erstellen
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan # ab Zeile 2 und Spalte 1 mit NaN füllen
df.iloc[4:, 2] = np.nan # ab Zeile 4 und Spalte 2 mit NaN füllen
print(df)
print('\n')
# Fehlende Werte mit dem Mittelwert je Spalte füllen
print(df.fillna(df.mean()))

          0         1         2
0  0.453738  0.745451  1.361484
1  1.130358  1.135592  0.371025
2 -0.548894       NaN  0.511977
3 -0.314432       NaN  0.244954
4  0.273316       NaN       NaN
5  0.121293       NaN       NaN


          0         1         2
0  0.453738  0.745451  1.361484
1  1.130358  1.135592  0.371025
2 -0.548894  0.940521  0.511977
3 -0.314432  0.940521  0.244954
4  0.273316  0.940521  0.622360
5  0.121293  0.940521  0.622360

## Duplikate entfernen

In [28]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
print(data)
data.duplicated()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [29]:
# Duplikate Löschen
# Die erste beobachtete Wertkombination wird behalten (Index 5)
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [30]:
data["v1"] = range(7)
print(data, '\n')
print('Löschen von Duplikaten anhand Spalte k1')
print(data.drop_duplicates(subset=["k1"]), '\n') 
print('Löschen von Duplikaten anhand Splate k1 und k2, der zuletzt vorkommende Wert soll behalten werden')
print(data.drop_duplicates(subset=["k1", "k2"], keep="last"))

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

Löschen von Duplikaten anhand Spalte k1
    k1  k2  v1
0  one   1   0
1  two   1   1

Löschen von Duplikaten anhand Splate k1 und k2, der zuletzt vorkommende Wert soll behalten werden
    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transformation durch Mappings

In [31]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [32]:
# Jedem Fleischprodukt wird die Tierart zugeordnet
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

# Die Tierart wird dem Dataframe als neue Spalte zugeordnet
data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

## Werte ersetzen

In [70]:
# Beispieldatensatz erstellen
data = pd.Series([1., -999., 2., -999., -1000., 3.])
print(data, '\n')

# -999 kann für fehlende Daten stehen, Pandas kann besser mit NaN umgehen
# -999 durch NaN ersetzen
print(data.replace(-999, np.nan))

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [72]:
# -999 und -1000 durch NaN ersetzen
print(data.replace([-999, -1000], np.nan), '\n')

# -999 und -1000 durch verschiedene Werte ersetzen
print(data.replace([-999, -1000], [np.nan, 0]))

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64